[package]
name = "dv"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["fs"] }
dotenvy = "0.15"
tower = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
